# This workflows will upload a Python Package using Twine when a release is created
# For more information see:
#  https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

# this will only upload to pypi when a new release is drafted.
# this is done through the github user interface
# before you can draft a new release you must create a tag
on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    # -------------------------------
    - name: Install pep517
      run: >-
        python -m
        pip install
        pep517
        --user
    # -------------------------------
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        pep517.build
        --source
        --binary
        --out-dir dist/
        .
    # -------------------------------
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}